### ISSUE TITLE
Note Created Date 1 Day Ahead

### ISSUE THREAD

**Issue by apratt101300** [Nelwell/lmn#40]
When creating notes, the date-posted field saves one day ahead of what it's supposed to. After creating a note on April 21st, it says it was posted on April 22nd.

**Comment by John151** [comment]
that's weird. I hate datetime stuff but I've just been reading a lot about it so I'll take a look right now

**Comment by John151** [comment]
So I just created a note (5:42 PM Central time) and it recorded the posting as 10:41 p.m., it looks like its saving time in GMT
